### PR TITLE
Improved retrieval of site lists and software versions

### PR DESCRIPTION
**Pull request by xartuu**
Hello again!
I'm back with some improvements. I have changed the method of downloading and displaying the list of sites and software versions. Now users don't have to type a command at each update to execute the commands contained in the `valet.sample.sh` file, because it's not needed!

The page list is scanned using the `scandir()` function. The script takes the contents of the Valet configuration file, looks through all the paths, looks for pages, and displays them. This is better than the `valet links` command, because it only displayed linked pages, but now you can see in the dashboard linked pages and pages in Valet paths.

To display the software version I used the `shell_exec()` function, this can be troublesome if someone has it disabled by default in `php.ini`, whereas it will show the current software version without the need to run `valet.sample.sh`. This should not be much of a problem since the Valet Dashboard is used locally and not in production.

I prepared a little surprise, which is the ability to copy the path to the site folder and the path to the ssl cetificate, if the site has one.

### CODE REVIEW

**Comment by frankyonnetti** [comment]
Hey Artur!

Man, these changes are great improvements. I love that you eliminated the need for the `valet.sh` script. And also, very cleaver to hook into the valet .config directory to get the list of sites.

For some reason the output for `dnsmasq -v 2>&1` is not displaying. And I'm getting an error message for the Valet version output `Valet requires Homebrew to be installed on your Mac.`. Any ideas why they may not be executing?

And out of curiosity, why write `5e2` instead of `500` in the `script.js` file, line 84?

**Comment by xartuu** [comment]
Glad to hear it, I tried ;D

I don't use macos, I use Windows 10 and Ubuntu 18.04 inside Windows (WSL2).
The valet I use is https://github.com/valeryan/valet-wsl. 
Everything works for me, you have screenshots [here](https://imgur.com/a/du7ZHl2).


> For some reason the output for `dnsmasq -v 2>&1` is not displaying. 

I honestly don't know why this command doesn't display anything to you.


> And I'm getting an error message for the Valet version output `Valet requires Homebrew to be installed on your Mac.`. Any ideas why they may not be executing?

Perhaps you don't have the `brew` command added to the `PATH` variable in the default shell, or perhaps PHP executing the `shell_exec()` function doesn't take the `PATH` variable into consideration and can't find the `brew` command.

`Valet requires Homebrew to be installed on your Mac.` is a Valet message.
https://github.com/laravel/valet/blob/master/cli/includes/compatibility.php#L25


> And out of curiosity, why write 5e2 instead of 500 in the script.js file, line 84?

Setting seconds as `5e3` or `2e4` is simply more readable to me than `5000` and `20000`, because there is no way to get confused.

**Comment by frankyonnetti** [comment]
Thanks, that was helpful. Funny thing is, I do have `PATH` setup correctly. So I did some searching and others suggested using the [putend function](https://www.php.net/manual/en/function.putenv.php). And after trying a few `PATH` options, I ended up adding this: `putenv('PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin');` to `index.php` and all is working correctly now.

Do you see any reason for not using `putend`?

**Comment by xartuu** [comment]
Try to avoid `putenv()`, because users may be on different systems, and paths to programs are OS-dependent.

Try again adding the `brew` command to the `$PATH` variable in the default shell. Try `/home/$USERNAME/.bashrc` or `/home/$USERNAME/.zshrc`. The user that Valet uses may be different from you, so type in the user that is displayed to you in the script below. Add the following content to these files.
```bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
```
Remember to restart Valet when changing the `$PATH` variable.


Try using the system() function instead of shell_exec(). Create a new file, say test.php with the contents below and run it in your browser. Send a screenshot of your results!

```php
<?php
var_dump(shell_exec('set'));
echo "<br>";
echo "<br>";
echo "<br>";

echo "Shell_exec() <br>";
echo "User: " . shell_exec('whoami') . "<br>" ;
echo "Shell: " . shell_exec('echo "$SHELL"') . "<br>";
echo "Which brew: " . shell_exec('which brew') . "<br>";
echo "<br>";
echo "Valet: " . shell_exec('valet -V 2>&1') . "<br>";
echo "Dnsmasq: " . shell_exec('dnsmasq -v 2>&1') . "<br>";
echo "MySQL: " . shell_exec('mysql --version 2>&1') . "<br>";
echo "Nginx: " . shell_exec('nginx -v 2>&1') . "<br>";
echo "Brew: " . shell_exec('brew -v 2>&1') . "<br>";

echo "<br>";
echo "<br>";

echo "System() <br>";
echo "User: " . system('whoami') . "<br>" ;
echo "Shell: " . system('echo "$SHELL"') . "<br>";
echo "Which brew: " . system('which brew') . "<br>";
echo "<br>";
echo "Valet: " . system('valet -V 2>&1') . "<br>";
echo "Dnsmasq: " . system('dnsmasq -v 2>&1') . "<br>";
echo "MySQL: " . system('mysql --version 2>&1') . "<br>";
echo "Nginx: " . system('nginx -v 2>&1') . "<br>";
echo "Brew: " . system('brew -v 2>&1') . "<br>";
```


Unfortunately I can't check if everything is working properly on macos or Linux and if it's just you getting this error.

**Comment by frankyonnetti** [comment]
I understand and appreciate you trying to help. 

I tested this on two Mac's with the same results in output... I'll keep digging as well.
 
Screen Shot 2021-10-25 at 10 00 32 AM

**Comment by xartuu** [comment]
I don't understand why the `which brew` command did not point to the path to brew, and `brew -v` displayed the version.


Execute the following line from your browser, it should show you the path, would you post it here?

```php
<?php
var_dump(shell_exec('echo $PATH'));
```

In my case it is
```php
string(61) "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin "
```


Type the `which brew` command in your console yet, I don't know where brew is located on macos.

**Comment by frankyonnetti** [comment]
This is what I get:
```php
string(44) "/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:. " 
```

**Comment by xartuu** [comment]
And where is the brew located?

**Comment by frankyonnetti** [comment]
Ha! In that path...
```
/usr/local/bin/brew
```

**Comment by xartuu** [comment]
I have a question that I can't find an answer to, why the `brew` command works, but `which brew` doesn't indicate where the command is located.

**Comment by frankyonnetti** [comment]
IDK. It's implemented differently on different OS's.
https://en.wikipedia.org/wiki/Which_(command)

Running `which which` on my Mac outputs: `which: shell built-in command`. I think in PowerShell on Windows it gives you a path?

**Comment by xartuu** [comment]
I use subsystem Windows (WSL) - Ubuntu 18.04.
It returns the same to me: `which: shell built-in command`.

**Comment by xartuu** [comment]
How did you install PHP? Mamp, brew, some other way?
Maybe you should install php another way?

**Comment by frankyonnetti** [comment]
I use Homebrew, Composer, and Node to install all the tools I need. Laraval also includes Homebrew as part of their documentation for [Valet installation](https://laravel.com/docs/valet#installation).

**Comment by frankyonnetti** [comment]
Hello,
I'm going to merge this in and give people the option to include their PATH in a non-tracked file.

**Comment by xartuu** [comment]
You solved it very cleverly. I'm glad it worked out!
I've been trying to discern more about this topic, but haven't found much about how to solve it differently.

**Pull request merged**
